First attempt at trying to get stackbuilder and associated tooling working using bundler
if you provide WITH_BUNDLER=true to bin/stacks, it should do the correc things to run
using bundle installed gems.

pre-commit hook also tries to intelligently work out whether to use bundler
or not based on the existence (or not) of the vendor/bundle directory

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,7 +1,21 @@
 #!/bin/sh
 
+which bundle > /dev/null
+HAVE_BUNDLER=$?
+if [ $HAVE_BUNDLER -eq 0 ]; then
+  [ -d 'vendor/bundle' ]
+  WITH_BUNDLER=$?
+fi
+
 echo -n "Running rake spec: "
-SPEC_OUTPUT=`rake spec 2>&1`
+if [ $WITH_BUNDLER -eq 0 ]; then
+  SPEC_OUTPUT=$(bundle exec rake spec 2>&1)
+elif which rake > /dev/null; then
+  SPEC_OUTPUT=`rake spec 2>&1`
+else
+  echo "[31mrake not found[0m" >&2
+  exit 1
+fi
 if [ $? -ne 0 ]; then
 	echo "[31mFAIL[0m" >&2
 	echo "$SPEC_OUTPUT" >&2
@@ -10,23 +24,30 @@ else
 	echo "[32mOK[0m"
 fi
 
-if which rubocop > /dev/null; then
-	# check only touched files
-	tmpdir=$(mktemp -d pre-commit.XXXXXXXXXX)
-	trap "rm -rf $tmpdir" EXIT
+# check only touched files
+tmpdir=$(mktemp -d pre-commit.XXXXXXXXXX)
+trap "rm -rf $tmpdir" EXIT
 
-	git diff --cached --name-only --diff-filter=ACM \
-	 | git checkout-index --stdin --prefix=$tmpdir/
+git diff --cached --name-only --diff-filter=ACM \
+  | git checkout-index --stdin --prefix=$tmpdir/
 
+if [ $WITH_BUNDLER -eq 0 ]; then
+  bundle exec rubocop $tmpdir/ || exit 1
+elif which rubocop > /dev/null; then
 	rubocop $tmpdir/ || exit 1
 else
-	echo "[31mrubocop not found[0m" >&2
-	exit 1
+  echo "[31mrubocop not found[0m" >&2
+  exit 1
 fi
 
 echo -n "Running stacks compile: "
 USER=`whoami`
-OUTPUT=`dev=true bin/stacks compile -c -- > /tmp/$USER-stacks-pre-commit`
+if [ $WITH_BUNDLER -eq 0 ]; then 
+  OUTPUT=`/usr/bin/env WITH_BUNDLER=true ruby bin/stacks compile -c -- > /tmp/$USER-stacks-pre-commit`
+else
+  OUTPUT=`dev=true bin/stacks compile -c -- > /tmp/$USER-stacks-pre-commit`
+fi
+
 RC=$?
 if [ $RC -ne 0 ]; then
   echo "FAIL"
